server:
 port: 8080

# ???????
spring:
    datasource:
        url: jdbc:mysql://43.136.70.112:3306/game?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password:  '@Guet123456'
        driver-class-name: com.mysql.cj.jdbc.Driver